version: "3.8"

services:
  lista:
    container_name: lista
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config/:/app/config/
  nginx_lista:
    container_name: nginx_lista
    image: nginx
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
